import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem, Box, Button } from '@chakra-ui/react'
import FAQ from '../components/FAQ';
import Link from 'next/link';
import NavBar from '../components/NavBar';
import SocialMediaIcons from '../components/SocialMediaIcons';
import AboutDetails from '../components/AboutDetails';
// import Team from '../components/AboutTeam';
import AboutTeamGrid from '../components/AboutTeamGrid';


export default function About() {

  return (
    <div className={styles.container}>
      <Head>
        <title>About Fourth Wave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png"/>
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          About Fourth Wave
        </h1>
        <p className={styles.description}>
          Fourth Wave DAO is a DeFi protocol running on the Polygon Network that helps women in need connect with people that can help.
        </p>
        <AboutDetails/>
        <a target="_blank" href="https://docs.fourthwavedao.ca/" rel="noopener noreferrer">
          <Button color="teal.600"
            variant="ghost"
            padding="10px 10px 10px 10px"
            marginTop={['10%', '5%', '5%']}
            whiteSpace='normal'
            fontWeight='bold'
            size="lg">Read our documentation</Button>
            </a>
        <Grid templateColumns='repeat(5, 1fr)' gap={4} p="5%">
          <GridItem colSpan={2} h='100' ><Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]}>
            <a target="_blank" href="https://medium.com/@alymarguerite/fourth-wave-dao-the-white-paper-dcdce2582a06" rel="noopener noreferrer">
              <Button
                colorScheme="teal"
                variant="ghost"
                bg='purple.100'
                whiteSpace='normal'
                w='100%'
                h='100%'
                p='5%'
                size="lg">The white paper</Button>
            </a>
          </Box>
          </GridItem>
          <GridItem colStart={4} colEnd={6} h='100' w='100%'><Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]} >
            <FAQ />
          </Box>
          </GridItem>
        </Grid>
        <h1 className={styles.title}>
         Meet our Team
        </h1>
            <AboutTeamGrid/>
        <span>
            <SocialMediaIcons />
        </span>
      </main>
      <footer className={styles.footer}>
        <span>
          <Link href="/" passHref>
            <a>
            <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>
  )
}