import React, { useState } from 'react';
import { Button, Grid, GridItem, Text } from '@chakra-ui/react'
import NavBar from '../components/NavBar';
import Head from 'next/head';
import styles from '../styles/Home.module.css'

export default function ApplicationConfirm() {

    const [type, setType] = useState("aunty")

    const handleType = (e) => {
        setType(e.target.value)
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Fourth Wave App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/FourthWave_Logo_Circle.png" />
            </Head>
            <NavBar />
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Application Confirmation
                </h1>
                <form action="/api/applicationConfirm" method="post" spellCheck="false" >
                    <Text fontSize='3xl' color='teal.600'>Please enter the required information below</Text>
                    <Grid h="100px" border='1px' borderColor='purple.100' borderRadius='15px' color='teal.700'>

                        <GridItem rowSpan={2} colSpan={4} bg='purple.50' borderRadius='15px 15px 0 0'>
                            <label htmlFor="id" >Application ID: </label>
                            <input type="text" id="nametext" name="id" maxLenght="30" minlength="20" required />
                        </GridItem>
                        <GridItem rowSpan={2} colSpan={4} bg='purple.50'>
                            <label htmlFor="telegram">Telegram ID handle (eg: @my_user_name): </label>
                            <input type="text" id="nametext" name="telegram" maxLenght="30" minlength="2" required/>
                        </GridItem>
                        <GridItem rowSpan={2} colSpan={4} bg='purple.50'>
                            <label htmlFor="type">Application Type: </label>
                            <select value={type} onChange={handleType} name="type">
                                <option value="aunty">Auntie</option>
                                <option value="candidate">Candidate</option>
                            </select>
                        </GridItem>
                        <GridItem rowSpan={4} colSpan={4} p="2" bg='purple.50' borderRadius='0 0 15px 15px'>
                            <Button type="submit" >Submit</Button>
                        </GridItem>

                    </Grid>
                </form>
            </main>
        </div>)
}