import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AuntyForm from "../components/AuntyForm";
import CandidateForm from '../components/CandidateForm';
import { Grid, GridItem, Button, Box } from '@chakra-ui/react';
import React, { useState, useContext } from "react";

//add links to medium articles, white paper

export default function Application() {

    const [isAuntyApplication, setIsAuntyApplication] = useState(false);
    const [isCandidateApplicaion, setIsCandidateApplicaion] = useState(false);
    const [openApplication, setOpenApplication] = useState(false);

    const handleApplication = (e) => {
        console.log(e.target.value)
        if (e.target.value === "aunty") {
            setIsAuntyApplication(true);
            setIsCandidateApplicaion(false);
            setOpenApplication(true);
        }
        if (e.target.value === "candidate") {
            setIsCandidateApplicaion(true);
            setIsAuntyApplication(false);
            setOpenApplication(true);
        }
    }

    const handleCloseApplication = () => {
        setOpenApplication(false);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Fourth Wave Application Form</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Fourth Wave Application Forms
                </h1>
                <p className={styles.description}>
                </p>
                {!openApplication && <Grid templateColumns='repeat(5, 1fr)' gap={4} pt="100px">
                    <GridItem colSpan={2} h='100' bg='purple.100'><Box boxShadow='xl' p='6' rounded='md' bg='white'>
                        <Button colorScheme="teal"
                            variant="ghost"
                            size="lg"
                            onClick={handleApplication}
                            value="aunty">Apply to become an Aunty</Button>
                    </Box>
                    </GridItem>
                    <GridItem colStart={4} colEnd={6} h='100' bg='purple.100'><Box boxShadow='xl' p='6' rounded='md' bg='white'>
                        <Button colorScheme="teal"
                            variant="ghost"
                            size="lg"
                            value="candidate"
                            onClick={handleApplication}>Apply to become a Candidate</Button>
                    </Box>
                    </GridItem>
                </Grid>}
                {openApplication &&
                    <Grid 
                        h='500px'
                        gap='1'
                        width='65%'>
                        <GridItem colStart={1} colEnd={12} h='80%' w="100%" bg='purple.100'>
                            <Box boxShadow='xl' pt='10' pl='50' pr='50' pb='30'rounded='md' bg='white'>
                            {isAuntyApplication && <AuntyForm />}
                            {isCandidateApplicaion && <CandidateForm />}
                            </Box>
                            <Box>
                            <Button colorScheme="teal"
                                variant="ghost"
                                size="lg"
                                value="candidate"
                                marginTop="20px"
                                onClick={handleCloseApplication}>Close Application (will not save)</Button>
                        </Box>
                        </GridItem>
                    </Grid>}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
                {/* <span>Some Footer Stuff</span> */}
            </footer>
        </div>
    )
}