import React, { useState, useContext } from 'react';
import { Context } from "../context/context";
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import Wallet from '../components/Wallet';
import { Grid, GridItem, Button, Box } from '@chakra-ui/react';
import Link from 'next/link';
import Nav from '../components/Nav';

export default function Home() {

  const { state, dispatch } = useContext(Context);

  return (
    <div className={styles.container}>
      <Head>
        <title>Fourth Wave App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Fourth Wave DAO
        </h1>
        <p className={styles.description}>
          {!state.user ? "Get started by connecting your wallet." : `Account ${state.user} succesfully connected`}

        </p>
        <Wallet />
        <Grid templateColumns='repeat(5, 1fr)' gap={4}>
          <GridItem colSpan={2} h='100' ><Box boxShadow='xl' p='6' bg='white'>
            <Link href="/about">
              <Button color="teal.600"
                variant="ghost"
                bg='purple.100'
                size="lg">Read About Our Mission</Button>
            </Link>
          </Box>
          </GridItem>
          <GridItem colStart={4} colEnd={6} h='100' ><Box boxShadow='xl' p='6' rounded='md' bg='white'>
            <Link href="/lottery">
              <Button color="teal.600"
                variant="ghost"
                bg='purple.100'
                size="lg">Play The Lottery Game!</Button>
            </Link>
          </Box>
          </GridItem>
        </Grid>
        <Link href="/application">
          <Button color="teal.600"
            variant="ghost"
            padding="50px 10px 50px 10px"
            marginTop="18%"
            whiteSpace='normal'
            size="lg">Apply HERE to become a candidate in our governance system, or an aunty in our nextwork.</Button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Link href="/" passHref>
            <a>
            <Image src="/images/FourthWave_Logo.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>
  )
}
