import React, { useContext, useState } from 'react';
import { Context } from "../context/context";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Wallet from '../components/Wallet';
import LotteryGrid from '../components/LotteryGrid';
import Link from 'next/link';
import NavBar from '../components/NavBar';
import { Button } from '@chakra-ui/react'
import SocialMediaIcons from '../components/SocialMediaIcons';
import LiFi from '../components/LiFiWidget';

export default function Lottery() {

  const { state, dispatch } = useContext(Context);
  let url = `https://widget.onramper.com?defaultCrypto=MATIC&color=2e7573&defaultFiat=CAD&apiKey=${process.env.NEXT_PUBLIC_ON_RAMP_API_KEY}`

  return (
    <div className={styles.container}>
      <Head>
        <title>Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Play the Lottery!
        </h1>
        <p className={styles.description}>
          Welcome Player - We are officially live on the Mainnet!
        </p>
        {!state.user ? 'Please connect your wallet to play' : `Account succesfully connected`}
        {!state.user ? <Wallet page='lottery' user='connected'/> : <Wallet page='lottery' user='connected'/>}
        <LotteryGrid />
        <p className={styles.description}>
          Need to purchase crypto?
        </p>
        <Button>
        <a href={url} target="_blank">Buy crypto</a>
        </Button>
        <p className={styles.description}>
          Not sure how to use the app?
        </p>
        <Button>
        <a target="_blank" href="https://docs.fourthwavedao.ca/" rel="noopener noreferrer">Fourth Wave documentation</a>
        </Button>
        <LiFi/>
        <span>
            <SocialMediaIcons />
        </span>
      </main>

      <footer className={styles.footer}>
        <span>
        <Link href="/" passHref>
            <a>
            <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>
  )
}