import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem, Box, Button, Divider } from '@chakra-ui/react'
import Link from 'next/link';
import NavBar from '../components/NavBar';
import SocialMediaIcons from '../components/SocialMediaIcons';


export default function Media() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Fourth Wave Press & Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png"/>
      </Head>
      <NavBar />
      <main className={styles.main}>
        <h1 className={styles.title}>
        Fourth Wave Press & Media
        </h1>
        <p className={styles.description}>
            We will be co-hosting a Twitter Space with Diversity in Blockchain & Crypto Altruism every two weeks!
        </p>
        <p className={styles.descriptionsm}>
            Follow us on <a href="https://twitter.com/FourthWaveDAO" target="_blank" className="twitter-link">Twitter</a> to make sure you don't miss and upcoming space.
        </p>
        <Divider />
        <Grid templateColumns='repeat(5, 1fr)' gap={4} p="5%">
          <GridItem colSpan={2} h='250' >
            <Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]}>
          {/* style="border-radius:12px"  */}
          <iframe src="https://open.spotify.com/embed/episode/5sPNHCZXpVBoSx94wdpnvR?utm_source=generator" width="100%" height="232" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
          </Box>
          </GridItem>
          <GridItem colStart={4} colEnd={6} h='250' w='100%'>
            <Box boxShadow='xl' p='6' rounded='md' bg='white' w={[100, 200, 300]} >
            <iframe src="https://open.spotify.com/embed/episode/3JMhQeKDRcOslqZOVNZfvu?utm_source=generator" width="100%" height="232" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
          </Box>
          </GridItem>
        </Grid>
        <Divider />
        <span>
            <SocialMediaIcons />
        </span>
      </main>
      <footer className={styles.footer}>
        <span>
          <Link href="/" passHref>
            <a>
            <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>
  )
}