import React, { useState, useContext } from 'react';
import { Grid, GridItem, Button, Box } from '@chakra-ui/react';
import Link from 'next/link';
import Nav from '../components/Nav';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css'

export default function Thankyou() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Fourth Wave App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/FourthWave_Logo_Circle.png" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Thank you, your application has been received!
        </h1>
        <Link href="/" passHref>
        <Button colorScheme="teal"
                            variant="ghost"
                            size="lg"
                            bg='purple.100'
                            whiteSpace='normal'
                            w='50%'
                            h='20%'
                            p='2%'
                            value="aunty">Home</Button>
                            </Link>
      </main>
      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Link href="/" passHref>
            <a>
              <Image src="/images/FourthWaveLogo_Transparent.png" alt="Vercel Logo" width={72} height={72} />
            </a>
          </Link>
        </span>
      </footer>
    </div>)
}